### ISSUE TITLE
您好，我这个问题仍然没有解决，请问这个类找不到的问题，我应该怎么调试胡总和导入什么包才可以解决呢

### ISSUE THREAD

**Issue by lkjnbghv** [DozzzeN/BESURE#2]
![image](https://user-images.githubusercontent.com/66630480/142560130-b1e7efb9-aabf-4ab3-ae3e-4911851dbf3e.png)

**Comment by lkjnbghv** [comment]
我试着编译合约，migrate合约到测试链，然后还是没有生成这个类，来请教请教您，这个到底怎么解决😁

**Comment by DozzzeN** [comment]
你好，感谢关注，这个是当时开发的时候写的部署合约的过程，希望可以帮到你
https://app.yinxiang.com/fx/d07cf132-3a34-4c3e-b330-60c18477431f

**Comment by lkjnbghv** [comment]
哇，真心感谢作者，我一定向您好好学习😛

**Comment by lkjnbghv** [comment]
我对您这篇文章十分感兴趣，您是一作吗，我是桂林电子科技大学的一名在读研究生，很高兴认识您

**Comment by DozzzeN** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DozzzeN/BESURE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 下午3:52
***@***.***&gt;;
抄送:&nbsp;"461367081 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [DozzzeN/BESURE] 您好，我这个问题仍然没有解决，请问这个类找不到的问题，我应该怎么调试胡总和导入什么包才可以解决呢 (Issue #2)





 
我对您这篇文章十分感兴趣，您是一作吗，我是桂林电子科技大学的一名在读研究生，很高兴认识您
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
